# Generated by Django 6.0.2 on 2026-02-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(blank=True, max_length=255, null=True)),
                ('spotify_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('duration', models.IntegerField()),
                ('raw_data', models.JSONField()),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
