# Generated by Django 6.0.2 on 2026-02-07 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('icon_url', models.URLField(blank=True, null=True)),
                ('playtime', models.IntegerField(default=0)),
                ('raw_data', models.JSONField()),
            ],
            options={
                'ordering': ['-playtime'],
            },
        ),
    ]
