# Generated by Django 6.0.2 on 2026-02-25 20:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_id', models.CharField(max_length=255, unique=True, verbose_name='app ID')),
                ('name', models.CharField(max_length=255, verbose_name='game name')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='icon URL')),
                ('playtime', models.FloatField(default=0.0, verbose_name='playtime (hours)')),
                ('raw_data', models.JSONField(verbose_name='raw steam JSON')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
                'ordering': ('-playtime',),
                'indexes': [models.Index(fields=['playtime'], name='games_game_playtim_6caec6_idx'), models.Index(fields=['name'], name='games_game_name_1d957c_idx')],
            },
        ),
        migrations.CreateModel(
            name='GameActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playtime', models.IntegerField(verbose_name='Playtime (minutes)')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='games.game', verbose_name='Game')),
            ],
            options={
                'verbose_name': 'game activity',
                'verbose_name_plural': 'game activities',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['created_at'], name='games_gamea_created_aa1ed6_idx'), models.Index(fields=['game', 'created_at'], name='games_gamea_game_id_0c24a1_idx')],
            },
        ),
    ]
