# Generated by Django 6.0.2 on 2026-02-21 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_gameactivity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('-playtime',), 'verbose_name': 'Game', 'verbose_name_plural': 'Games'},
        ),
        migrations.AlterModelOptions(
            name='gameactivity',
            options={'ordering': ('-created_at',), 'verbose_name': 'game activity', 'verbose_name_plural': 'game activities'},
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='app ID'),
        ),
        migrations.AlterField(
            model_name='game',
            name='icon_url',
            field=models.URLField(blank=True, null=True, verbose_name='icon URL'),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=255, verbose_name='game name'),
        ),
        migrations.AlterField(
            model_name='game',
            name='playtime',
            field=models.FloatField(default=0.0, verbose_name='playtime (hours)'),
        ),
        migrations.AlterField(
            model_name='game',
            name='raw_data',
            field=models.JSONField(verbose_name='raw steam JSON'),
        ),
        migrations.AlterField(
            model_name='gameactivity',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='games.game', verbose_name='Game'),
        ),
        migrations.AlterField(
            model_name='gameactivity',
            name='playtime',
            field=models.IntegerField(verbose_name='Playtime (minutes)'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['playtime'], name='games_game_playtim_6caec6_idx'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['name'], name='games_game_name_1d957c_idx'),
        ),
        migrations.AddIndex(
            model_name='gameactivity',
            index=models.Index(fields=['created_at'], name='games_gamea_created_aa1ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='gameactivity',
            index=models.Index(fields=['game', 'created_at'], name='games_gamea_game_id_0c24a1_idx'),
        ),
    ]
